dubbo:
  application:
    name:  dubbo-consumer
  registry:
    address: 10.0.111.18:2181
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 3000

server:
  port: 8061

